name: Nix

on:
  push:
  workflow_dispatch:

permissions:
  id-token: "write"
  contents: "read"

env:
  NIX_ABORT_ON_WARN: "1"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-24.04"
          - "ubuntu-24.04-arm"
          - "macos-15"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: DeterminateSystems/nix-installer-action@e4760a7aa015308e829d7c47136ff61576d1aacf
        with:
          determinate: true
          extra-conf: |
            accept-flake-config = true
            allow-import-from-derivation = false

      - name: Check flake
        run: |
          nix flake check --keep-going --print-build-logs github:${{ github.repository }}/${{ github.sha }}
